name: "gh-release-changelog"
description: "GitHub Release by Changelog"
inputs:
  token: # id of input
    description: "github token"
    required: true
    default: ${{ secrets.GITHUB_TOKEN }}
#outputs:
#  time: # output will be available to future steps
#    description: "The current time after waiting"
runs:
  using: "node12"
  main: "dist/index.js"
