name: "CI"

on:
  pull_request:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: env
      - run: npm ci
      - run: npm test

  gh-release-changelog:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'v1.0.2-beta.2'
          draft: true
          checkStandardVersion: false
          checkPkgAvailable: false
