name: "CI"

on:
  pull_request:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: env
      - run: npm ci
      - run: npm test

  gh-release-changelog:
    # test action works running from the graph
    runs-on: ubuntu-latest
    needs: [test]
    env:
      ACTIONS_RUNNER_DEBUG: true
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          ACTIONS_STEP_DEBUG: true
